### ISSUE TITLE
Write Account class which implements Account Information functions.

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#1]
Convert existing code (`Account.mqh`) into class which implements all listed [Account Information](https://docs.mql4.com/account) methods using the same name as in MT4 documentation (some of them are already there). These methods should work for both MQL4 (MT4) and MQL5 (MT5) platforms (see the [MT5 docs](https://www.mql5.com/en/docs/constants/environment_state/accountinformation)). Remove anything else which is not related to Account methods.

Language: MQL 4&5

To compile for each version, you need to install both platforms ([MT4](http://www.metatrader4.com/) & [MT5](http://www.metatrader5.com/)) and compile using [MetaEditor](http://www.metatrader5.com/en/metaeditor/help/development/compile).

**Comment by LemonBoy** [comment]
This [1] one's missing some methods which, from my limited understanding, require something more than a simple stub to be replaced.

[1] https://ptpb.pw/Zv90

**Comment by kenorb** [comment]
The code is fine.

The [`AccountStopoutLevel`](https://docs.mql4.com/account/accountstopoutlevel) depending on [`AccountStopoutMode`](https://docs.mql4.com/account/accountstopoutmode), so if you've different mode on two different platform, the output can vary. Same for [`AccountFreeMarginCheck`](https://docs.mql4.com/account/accountfreemargincheck), it probably rely on [`AccountFreeMarginMode`](https://docs.mql4.com/account/accountfreemarginmode). This [porting table](https://sites.google.com/site/ctesterformt4/mt5/mt5-examples/mql4_to_mql5/mql4-to-mql5-porting-table) may help. If not, add the `@fixme` and you may move on, so this could be fixed later on, on some concrete use case when testing some specific code as part of another task.
