### ISSUE TITLE
Create a class to load, modify and save data values

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#10]
Create a `Data` class with methods to add new data values of any format, to change the values on instance level and to save into the file, then restore the data from the file.

Example usage:

1.  `data = new Data();` // No argument, so start from scratch.
1. `data.SetValue('max_spread', 10);` // Format: data.SetValue(string key, dynamic value);
1. `data.SetValue('ratio', 0.5);`
1. `data.SetValue('msg', "Foo");`
1. `data.SetValue('msg', "Bar");`
1. `ratio = data.GetValueDouble('ratio');` // 0.5 // Wrapper for each format value.
1. `msg = data.GetValueString('msg');` // Bar
1. `is_success = data.Save('data.bin');` // Save all mixed data into file (replacing any existing file).
1. `data = new Data('data.bin');` // Load all data into class array and return the instance.
1. `max_spread = data.GetValueInteger('max_spread');` // 10

See: [FileReadArray](https://docs.mql4.com/files/filereadarray)/[FileReadArray](https://www.mql5.com/en/docs/files/filereadarray), [FileWriteArray](https://docs.mql4.com/files/filewritearray)/[FileWriteArray](https://www.mql5.com/en/docs/files/filewritearray)

Est. 6-8h

**Comment by lu43n** [comment]
Done: 8h
