### ISSUE TITLE
Write DateTime class which implements Date and Time functions.

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#2]
Convert existing code (`DateTime.mqh`) into class which implements all listed [Date and Time](https://docs.mql4.com/dateandtime) methods using the same name as in MT4 documentation (some of them are already there). These methods should work for both MQL4 (MT4) and MQL5 (MT5) platforms. Remove anything else which is not related to Date and Time.

E.g. `Hour()` method should return `Hour()` value in MT4, but [`MqlDateTime`](https://www.mql5.com/en/docs/constants/structures/mqldatetime) in MT5.

Language: MQL 4&5

To compile for each version, you need to install both platforms ([MT4](http://www.metatrader4.com/) & [MT5](http://www.metatrader5.com/)) and compile using [MetaEditor](http://www.metatrader5.com/en/metaeditor/help/development/compile).

**Comment by LemonBoy** [comment]
Something like [1] ? It provides some glue for MQL5's missing functions, I did test it with a simple script and it works just fine and moth MQL{4,5} found no syntax errors.

[1] https://ptpb.pw/IF5x

**Comment by kenorb** [comment]
@LemonBoy Sorry for late reply. Yes, however I expect those methods wrapped in the [class](https://docs.mql4.com/basis/types/classes), so I could call the methods consistently from the other file without having worrying about `#ifdef`. In other words I just want to call `DateTime::Day()` from both MQL4/MQL5 file and I expect the same result.

E.g.

```
class DateTime {

  int Day() {
    #ifdef __MQL5__
       MqlDateTime dt;
       TimeCurrent(dt);
       return(dt.day);
    #else
      return Day();
    #endif
  }
  // ... more methods
}
```

**Comment by LemonBoy** [comment]
So, something like this [1] ?

[1] https://ptpb.pw/jaGL

**Comment by kenorb** [comment]
That's correct. I think making indentation for `#ifdef` would look better if it's aligned with the code. Check for [other](https://docs.mql4.com/dateandtime) date related functions as well. If there is any blocker function that can't be back-ported easily, add `@todo` so you may ignore.

**Comment by LemonBoy** [comment]
`TimeTradeServer` has been added in MQL5 and has no equivalent for MQL4, I'll shift the # tokens once I submit a PR. The other options I didn't bring into the class are the ones that are available for both the versions and making a wrapper sounds quite pointless, no ?

**Comment by kenorb** [comment]
If `TimeTradeServer` not there in MQL4, you can return the value for MQL5 and NULL for MQL4 with some comment or todo, probably this won't be used anyway.

**Comment by kenorb** [comment]
Looks fine. I'll test it later on. Thanks.
