### ISSUE TITLE
Fix CI tests

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#20]
Two CI tests to fix: [Appveyor](https://ci.appveyor.com/project/kenorb/ea31337-classes/build/1.0.19-master) & [Travis](https://travis-ci.org/EA31337/EA31337-classes/builds/195043679)

Files to fix: *.mqh

Language: MQL (you need to install [Metaeditor](http://www.metatrader5.com/en/download) to compile the files). After installation, copy/clone the repo under MQL5 or MQL5/Include folder of the platform, so you can open them and compile. Other dependent repos should be cloned recursively into MQL5/Include (e.g. [strategies](https://github.com/EA31337/EA31337-strategies)).

The redefinition/already-defined errors happens, because include-files are including another .mqh files (`<>` instead of `""`) and compiler probably doesn't recognise that these are the same files. After that there should be only very few errors.

**Comment by kenorb** [comment]
codemill$44

**Comment by ryu0** [comment]
Is this still needing a resolution? Also, where is the bounty information?

**Comment by kenorb** [comment]
I think the current build has been fixed already at https://ci.appveyor.com/project/kenorb/ea31337-classes
Let me double check this this week.

**Comment by kenorb** [comment]
Looks like fixed.
