### ISSUE TITLE
Order: Structure have objects and cannot be copied

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#29]
File: `Order.mqh`

Code:

```
void Order(const OrderEntry &_order) {
  order = _order;
}
```

The error happens during compilation in MT4.

Code commented in a8925756d5d7055e976828948b2add67eecbac2c, should be uncommented to reproduce.

**Comment by nseam** [comment]
Looks like it's now compiling in both, MT4 and MT5 without errors/warning.
