### ISSUE TITLE
Zero divide in Market.mqh (181,53)

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#301]
- Tag: v1.079
- Symbol: WINQ20
- Tf: M1
- Related: https://github.com/EA31337/EA31337/issues/219

**Comment by psynando012** [comment]
is it not necessary to change something in the market.mqh file?

**Comment by kenorb** [comment]
> is it not necessary to change something in the market.mqh file?

Yes, this method:
```
  static double GetTradeDistanceInPips(string _symbol) {
    return (double) (GetTradeDistanceInPts(_symbol) / GetPointsPerPip(_symbol));
  }
```
to avoid division by zero, so basically `GetPointsPerPip(_symbol)` cannot be zero.

**Comment by kenorb** [comment]
Probably to:
```
return (double) (GetPointsPerPip(_symbol) > 0 ? (GetTradeDistanceInPts(_symbol) / GetPointsPerPip(_symbol)) : 0);
```

**Comment by psynando012** [comment]
return (double) (GetPointsPerPip(_symbol) > 0 ? (GetTradeDistanceInPts(_symbol) / GetPointsPerPip(_symbol)) : 0); 

would that be the solution option?
