### ISSUE TITLE
Orders::OrdersTotal() missing

### ISSUE THREAD

**Issue by biohazardxxx** [EA31337/EA31337-classes#426]
The replacement for OrdersTotal() which should be Orders::OrdersTotal() is missing.
Not sure what more info is required so please let me know.

**Comment by kenorb** [comment]
- The `OrdersTotal()` method has been moved to Trade class. So you can call it as `Trade::OrdersTotal()`.
- `Orders` class is not recommended to use (it may be removed in the future), please use `Trade` class instead to manage orders.

**Comment by biohazardxxx** [comment]
Thanks that works. 👍 Would be good to have this updated in the README.md under "MQL4 to MQL5 conversion".
