### ISSUE TITLE
Comment for _level is incorrect

### ISSUE THREAD

**Issue by hrdrq** [EA31337/EA31337-classes#638]
I guess `_level` is not bitwise AND operation, and is percentage value?
https://github.com/EA31337/EA31337-classes/blob/86dc933a1ecd854c93b9b98e87326507d8e58188/Strategy.mqh#L1014-L1042

**Comment by kenorb** [comment]
Yes, it's incorrect.
It's not bitwise, but a float.
It's not necessary a percentage (it's used as a percentage of indicator value change where there is no primary usage), it depends on the strategy (can be used for anything). For example in RSI, can be used to set the levels of signal (e.g. 20 level means 30 vs 70).
Unfortunately a lot of block comments are outdated, so they need to be corrected at some point.

**Comment by hrdrq** [comment]
Thanks. Is there an effective way to report incorrect comments like it?

**Comment by kenorb** [comment]
Fixed in [v2.010](https://github.com/EA31337/EA31337-classes/releases/tag/v2.010).
